# Generated by Django 4.0.5 on 2022-08-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(max_length=255, unique=True)),
                ('longitude', models.FloatField(max_length=255, unique=True)),
                ('image1', models.ImageField(max_length=255, unique=True, upload_to='')),
                ('image2', models.ImageField(max_length=255, unique=True, upload_to='')),
                ('town', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(default='Nigeria', max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Places',
                'ordering': ('name',),
            },
        ),
    ]
