# Generated by Django 4.0.5 on 2022-08-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_alter_place_image1_alter_place_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='town',
            field=models.CharField(max_length=255),
        ),
    ]
